### ISSUE TITLE
AssertionError: expected network ID 1, got NaN

### ISSUE THREAD

**Issue by vikmeup** [makerdao/migrate-dashboard#12]
Wallet: Trust Wallet
How do you guys check network id? Not sure why would this failed, `net_version` seems to return data, maybe it's a string or int? 

![EJrJpJyX0AEjc7W](https://user-images.githubusercontent.com/1641795/69078955-d09bec00-09ed-11ea-9741-13c8559cb363.jpeg)

**Comment by levity** [comment]
Hi, thanks for reporting. We check `window.ethereum.networkVersion`. What would you want us to be checking for Trust Wallet?

**Comment by rstormsf** [comment]
@levity you should never use sync method from web3.js
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md

please use more standard compliant version:
`ethereum.send(method, params)` 
in your case:
`await ethereum.send('net_version', [])`

**Comment by vikmeup** [comment]
`window.ethereum.chainId` seems to work 

We are going to add `window.ethereum.networkVersion` in the next version - it should return `int` - correct?

Also did you consider using chain id? as network version is not gonna work with ETC chain well

**Comment by vikmeup** [comment]
@levity do you know if this related: https://twitter.com/ITMCitizen/status/1196504275947589632 ?

**Comment by levity** [comment]
> @levity do you know if this related: https://twitter.com/ITMCitizen/status/1196504275947589632 ?

Yes, looks like it; I'll apply this same fix there as well.

**Comment by vikmeup** [comment]
Confirmed, fixed! Thank you!
