### ISSUE TITLE
unlock sai tx failed Invalid request: value key missing

### ISSUE THREAD

**Issue by elopio** [makerdao/migrate-dashboard#15]
I'm trying to migrate my SAI to multi-collateral DAI using walletconnect and the gnosis safe.
When I check the "Unlocking SAI" checkbox, it fails:

```
unlock sai tx failed Invalid request: {"id":[...],"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"[...]","to":"0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359","gasPrice":"0x2540be400","gasLimit":"0x1166c","nonce":"0x1","data":"0x095ea7b3000000000000000000000000c73e0383f3aff3215e6f04b0331d58cecf0ab8490000000000000000000000000000000000000000000000069d17119dc5a80000"}]} (value key missing)
```
I'm on Debian, Firefox 71.0b9.

**Comment by levity** [comment]
Thanks for reporting the issue. We're looking into it.

**Comment by levity** [comment]
@elopio I was unable to reproduce this issue using WalletConnect with Chrome on MacOS and Gnosis Safe on iOS. Are you still having this problem? If so, what desktop and mobile OS's are you using?

**Comment by elopio** [comment]
Yes. I've just tried again.
I'm using Debian 10, Firefox 71.0b9, Android 9, Gnosis Safe 1.8.1.

**Comment by sorenp** [comment]
Recreated with Gnosis Safe on Android 8.1.0 & Desktop in Chrome on MacOS Mojave 10.14.6

**Comment by levity** [comment]
@b-pmcg is able to reproduce this in a development environment so we should have a fix soon.

**Comment by elopio** [comment]
good news! Thank you.

**Comment by levity** [comment]
@elopio We've deployed a fix; please try again.

**Comment by elopio** [comment]
Thanks for the fix, it works.
I've migrated :sunglasses:
